name = "xray-gateway-portal"
main = "src/index.js"
compatibility_date = "2026-07-15"

[assets]
directory = "./public"
run_worker_first = ["/start"]
not_found_handling = "404"

[vars]
GITHUB_OWNER = "350001"
GITHUB_REPO = "001"
WORKFLOW_FILE = "xray-warp-gateway.yml"
GITHUB_BRANCH = "main"